name: 'release-webhapp'
on:
  push:
    tags:
      - 'happ-v[0-9]+.[0-9]+.[0-9]+'
      - 'happ-v[0-9]+.[0-9]+.[0-9]+-[a-z]+'
      - 'happ-v[0-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+'

jobs:
  publish-happ:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    outputs:
      releaseId: ${{ steps.create-release.outputs.id }}
    steps:
      - uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          install_url: https://releases.nixos.org/nix/nix-2.23.0/install

      - uses: cachix/cachix-action@v15
        with:
          name: holochain-ci

      - name: Install and build
        run: |
          nix-store --gc
          nix develop --command bash -c "holochain --version && npm install && npm run pack:webhapp"
          shasum -a 256 ./workdir/sharefeed.happ
          shasum -a 256 ./workdir/sharefeed.webhapp

      - name: Retrieve version
        run: |
          echo "APP_VERSION=$(cat package.json | grep -oP '(?<="version": ")[^"]*')" >> $GITHUB_OUTPUT
        id: version

      - id: create-release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: false
          artifacts: workdir/sharefeed.webhapp,workdir/sharefeed.happ
          body: 'See assets below to download and install this version.'
          name: ShareFeed hApp v${{ steps.version.outputs.APP_VERSION }}
          tag: happ-v${{ steps.version.outputs.APP_VERSION }}
          prerelease: true
          draft: true
